site_name: Moje portfolio
site_author: Denis Karankevich

repo_name: RedGamer887/portfolio_ai
repo_url: https://github.com/RedGamer887/portfolio_ai

theme:
  name: material
  icon:
    logo: material/account-circle
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
  features:
    - palette

nav: []

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - i18n:
      default: pl
      languages:
        - name: Polski
          locale: pl
          build: true
          default: true
        - name: English
          locale: en
          build: true