site_name: Moje portfolio
site_author: Denis Karankevich

repo_name: RedGamer887/ds_portfolio
repo_url: https://github.com/RedGamer887/ds_portfolio

theme:
  name: material
  icon:
    logo: material/account-circle
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
  features:
    - palette

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - i18n:
      languages:
        - locale: pl
          name: Polish
          default: true
          build: true
        - locale: en
          name: English
          build: true