site_name: Moje portfolio
site_author: Denis Karankevich

repo_name: RedGamer887/portfolio_ai
repo_url: https://github.com/RedGamer887/portfolio_ai

theme:
  name: material
  icon:
    logo: material/account-circle
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
  features:
    - palette

nav:
  - PL:
      - Główna strona: pl/index.md
      - Projekty z kursu:
          - "NaszGPT": pl/naszgpt/index.md
          - "Audio Notatki": pl/audio_notes/index.md
      - Projekty indywidualne:
          - "Audio & Wideo": pl/audio_video_summary/index.md
          - "Poszukiwanie pracy": pl/oferty_pracy/index.md
  - EN:
      - Home: en/index.md
      - Course Projects:
          - "NaszGPT": en/naszgpt/index.md
          - "Audio Notes": en/audio_notes/index.md
      - Personal Projects:
          - "Audio & Video": en/audio_video_summary/index.md
          - "Job Search": en/oferty_pracy/index.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - i18n:
      default: pl
      languages:
        - name: Polski
          locale: pl
          build: true
          default: true
        - name: English
          locale: en
          build: true